//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowPlacementExample.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<WindowPlacement xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <Length>0</Length>
  <Flags />
  <ShowCommand>Hide</ShowCommand>
  <MinimizedPosition>
    <X>0</X>
    <Y>0</Y>
  </MinimizedPosition>
  <MaximizedPosition>
    <X>0</X>
    <Y>0</Y>
  </MaximizedPosition>
  <NormalBounds>
    <Left>0</Left>
    <Top>0</Top>
    <Right>0</Right>
    <Bottom>0</Bottom>
  </NormalBounds>
</WindowPlacement>")]
        public global::WpfWindowPlacement.WindowPlacement MainWindowPlacement {
            get {
                return ((global::WpfWindowPlacement.WindowPlacement)(this["MainWindowPlacement"]));
            }
            set {
                this["MainWindowPlacement"] = value;
            }
        }
    }
}
