name: Publish new version

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish to NuGet
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: WpfWindowPlacement/WpfWindowPlacement.csproj
          VERSION_FILE_PATH: Directory.Build.props
          NUGET_KEY: ${{ secrets.NUGET_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.publish_nuget.outputs.PACKAGE_PATH != null }} # Was a NuGet package created?
        with:
          tag_name: ${{ steps.publish_nuget.outputs.VERSION }}
          files: ${{ steps.publish_nuget.outputs.PACKAGE_PATH }}
